<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright 2021 Kaur Palang (original template)
  Copyright 2025 Saga IT, LLC
  
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.saga-it</groupId>
        <artifactId>mirthsync-plugin</artifactId>
        <version>0.0.3</version>
    </parent>

    <artifactId>server</artifactId>

    <properties>
        <javax-servlet.version>4.0.1</javax-servlet.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.saga-it</groupId>
            <artifactId>shared</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>${javax-servlet.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>clj-http</groupId>
            <artifactId>clj-http</artifactId>
            <version>3.10.1</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.httpcomponents</groupId>
                    <artifactId>httpcore</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.httpcomponents</groupId>
                    <artifactId>httpclient</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.httpcomponents</groupId>
                    <artifactId>httpmime</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-codec</groupId>
                    <artifactId>commons-codec</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-io</groupId>
                    <artifactId>commons-io</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>clj-jgit</groupId>
            <artifactId>clj-jgit</artifactId>
            <version>1.1.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>bcutil-jdk18on</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>bcpkix-jdk18on</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>bcprov-jdk18on</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>clj-tuple</groupId>
            <artifactId>clj-tuple</artifactId>
            <version>0.2.2</version>
        </dependency>
        <dependency>
            <groupId>environ</groupId>
            <artifactId>environ</artifactId>
            <version>1.2.0</version>
        </dependency>
        <dependency>
            <groupId>potemkin</groupId>
            <artifactId>potemkin</artifactId>
            <version>0.4.5</version>
        </dependency>
        <dependency>
            <groupId>riddley</groupId>
            <artifactId>riddley</artifactId>
            <version>0.1.12</version>
        </dependency>
        <dependency>
            <groupId>slingshot</groupId>
            <artifactId>slingshot</artifactId>
            <version>0.12.2</version>
        </dependency>
        <dependency>
            <groupId>com.googlecode.javaewah</groupId>
            <artifactId>JavaEWAH</artifactId>
            <version>1.2.3</version>
        </dependency>
        <dependency>
            <groupId>net.i2p.crypto</groupId>
            <artifactId>eddsa</artifactId>
            <version>0.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpasyncclient</artifactId>
            <version>4.1.4</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient-cache</artifactId>
            <version>4.5.10</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpcore-nio</artifactId>
            <version>4.4.10</version>
        </dependency>
        <dependency>
            <groupId>org.apache.sshd</groupId>
            <artifactId>sshd-osgi</artifactId>
            <version>2.11.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.sshd</groupId>
            <artifactId>sshd-sftp</artifactId>
            <version>2.11.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.sshd</groupId>
                    <artifactId>sshd-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpg-jdk18on</artifactId>
            <version>1.77</version>
        </dependency>
        <dependency>
            <groupId>org.clojure</groupId>
            <artifactId>clojure</artifactId>
            <version>1.10.1</version>
        </dependency>
        <dependency>
            <groupId>org.clojure</groupId>
            <artifactId>core.specs.alpha</artifactId>
            <version>0.2.44</version>
        </dependency>
        <dependency>
            <groupId>org.clojure</groupId>
            <artifactId>data.xml</artifactId>
            <version>0.0.8</version>
        </dependency>
        <dependency>
            <groupId>org.clojure</groupId>
            <artifactId>data.zip</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.clojure</groupId>
            <artifactId>spec.alpha</artifactId>
            <version>0.2.176</version>
        </dependency>
        <dependency>
            <groupId>org.clojure</groupId>
            <artifactId>tools.cli</artifactId>
            <version>1.0.206</version>
        </dependency>
        <dependency>
            <groupId>org.clojure</groupId>
            <artifactId>tools.logging</artifactId>
            <version>1.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jgit</groupId>
            <artifactId>org.eclipse.jgit</artifactId>
            <version>6.8.0.202311291450-r</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jgit</groupId>
            <artifactId>org.eclipse.jgit.gpg.bc</artifactId>
            <version>6.8.0.202311291450-r</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jgit</groupId>
            <artifactId>org.eclipse.jgit.ssh.apache</artifactId>
            <version>6.8.0.202311291450-r</version>
        </dependency>
        <dependency>
            <groupId>org.nrepl</groupId>
            <artifactId>incomplete</artifactId>
            <version>0.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.saga-it</groupId>
            <artifactId>mirthsync</artifactId>
            <version>3.5.1</version>
        </dependency>

        <dependency>
            <groupId>com.mirth.connect</groupId>
            <artifactId>mirth-core-server-plugins</artifactId>
            <version>${mirth.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.mirth.connect</groupId>
            <artifactId>mirth-core-models</artifactId>
            <version>${mirth.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.mirth.connect</groupId>
            <artifactId>mirth-core-client-base</artifactId>
            <version>${mirth.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.mirth.connect</groupId>
            <artifactId>mirth-core-util</artifactId>
            <version>${mirth.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.6.1</version>
                <executions>
                    <execution>
                        <id>copy-runtime-deps</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <includeScope>runtime</includeScope>
                            <includeArtifactIds>${saga.runtime.artifacts}</includeArtifactIds>
                            <outputDirectory>${project.build.directory}/runtime-libs-selected</outputDirectory>
                            <useRepositoryLayout>false</useRepositoryLayout>
                            <includeTypes>jar</includeTypes>
                            <excludeTransitive>true</excludeTransitive>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>